### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by kercre123**
Add rpm install command, replace `apt purge` as it never worked for me

### CODE REVIEW

**Review by bkerler — CHANGES_REQUESTED** [review]
Thanks for updating the Fedora instructions. However "apt purge ModemManager" is still highly recommended for debian/ubuntu derivates. Also for the latest Ubuntu, there is no python2 anymore, so python is recommended.

**Comment by kercre123** [comment]
> Thanks for updating the Fedora instructions. However "apt purge ModemManager" is still highly recommended for debian/ubuntu derivates. Also for the latest Ubuntu, there is no python2 anymore, so python is recommended.

I'll revert those. `sudo apt purge ModemManager` never worked for me on Ubuntu or Debian, it doesn't appear to be an apt package. It doesn't hurt to try though.

**Comment by bkerler** [comment]
Thanks ;) Looks great now.

**Comment by CyberMan571** [comment]
image
@bkerler 
it works on me!

**Pull request merged**
