### PR TITLE
Reformat

### PR DESCRIPTION
**Pull request by danielkutik**
This is based on my previous changes (pull request #55).

While reviewing your code i did a lot of minor lint fixes and reformat... Feel free to reject...

### CODE REVIEW

**Comment by bkerler** [comment]
Sorry, I cannot add this commit, as it doesn't seem to be right. Why are you adding the first and the last usable sector ?
The first sector is the sector after the gpt that can be used. The last sector defines the last sector that can be used. Adding both would mean you write past the last possible sector. Maybe your gpt is broken ?

**Comment by bkerler** [comment]
The lint fixes seem fine to me, but it would be better to separate those from additional fixes.

**Comment by bkerler** [comment]
I've added your patch 294758f and put your git nick into the comment.

**Comment by danielkutik** [comment]
Closing this one since you have some done of this work on master already. Will review 241d9dd with @enggmind and do another pull request if required.

**Pull request closed without merging**
